import { precacheAndRoute } from 'workbox-precaching';

// Inject precache manifest for static assets generated by Workbox
precacheAndRoute(self.__WB_MANIFEST || []);
self.addEventListener('push', function (event) {
  if (event.data) {
    const data = event.data.json();
    const options = {
      body: data.body,
      icon: data.icon || '/icon.png',
      badge: '/badge.png',
      vibrate: [100, 50, 100],
      data: {
        dateOfArrival: Date.now(),
        primaryKey: '2',
      },
    };
    event.waitUntil(self.registration.showNotification(data.title, options));
  }
});

self.addEventListener('notificationclick', function (event) {
  console.log('Notification click received.');
  event.notification.close();
  // event.waitUntil(clients.openWindow('<https://your-website.com>'));
});
